# Generated by Django 3.2 on 2021-04-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=12)),
                ('version', models.CharField(max_length=55, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('date_of_issue', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('in stock', 'в наличии'), ('out of stock', 'нет в наличии')], max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='games')),
                ('price', models.PositiveIntegerField(default=0)),
                ('type', models.ManyToManyField(to='main1.Type')),
            ],
        ),
    ]
