# Generated by Django 3.2 on 2021-04-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('торг уместен', 'в наличии'), ('out of stock', 'нет в наличии')], max_length=20),
        ),
    ]
