# Generated by Django 3.2 on 2021-04-14 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=55)),
                ('city', models.CharField(max_length=44)),
                ('email', models.EmailField(max_length=33)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main1.game')),
            ],
        ),
    ]
